//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr17Danilov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.OrderItems = new HashSet<OrderItems>();
            this.ProductReviews = new HashSet<ProductReviews>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public decimal Discount { get; set; }
        public int ManufacturerId { get; set; }
        public int ProductTypeId { get; set; }
        public double Rating { get; set; }
        public bool IsFrozen { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual ICollection<ProductReviews> ProductReviews { get; set; }
        public virtual ProductTypes ProductTypes { get; set; }
    }
}
