//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr17Danilov
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceTypes
    {
        public ServiceTypes()
        {
            this.Appointments = new HashSet<Appointments>();
            this.MasterServices = new HashSet<MasterServices>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int DurationMinutes { get; set; }
    
        public virtual ICollection<Appointments> Appointments { get; set; }
        public virtual ICollection<MasterServices> MasterServices { get; set; }
    }
}
