//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr17Danilov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Appointments = new HashSet<Appointments>();
            this.Appointments1 = new HashSet<Appointments>();
            this.MasterServices = new HashSet<MasterServices>();
            this.Orders = new HashSet<Orders>();
            this.ProductReviews = new HashSet<ProductReviews>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
        public bool IsFrozen { get; set; }
    
        public virtual ICollection<Appointments> Appointments { get; set; }
        public virtual ICollection<Appointments> Appointments1 { get; set; }
        public virtual ICollection<MasterServices> MasterServices { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<ProductReviews> ProductReviews { get; set; }
    }
}
